language: ruby

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

script:
  - chef exec rake

after_script:

env:
  global:
    # - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
rvm:
  - 2.5.3
