name             'code_generator'
maintainer       'Partner Engineering at Chef Software, Inc.'
maintainer_email 'partnereng@chef.io'
license          'Apache 2 License'
description      'Generates the a cookbook for the cookbook-guide'
long_description 'Generates the a cookbook for the cookbook-guide'
version          '1.1.1'

issues_url 'https://github.com/chef-partners/cookbook-guide-generator/issues'
source_url 'https://github.com/chef-partners/cookbook-guide-generator'
