name             'code_generator'
maintainer       'Partner Engineering at Chef Software, Inc.'
maintainer_email 'partnereng@chef.io'
license          'Apache 2 License'
description      'Generates Chef code for Chef DK'
long_description 'Generates Chef code for Chef DK'
version          '1.0.0'

issues_url 'https://github.com/chef-partners/cookbook-guide-generator/issues'
source_url 'https://github.com/chef-partners/cookbook-guide-generator'
